### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by choosen** [Krakow-Ruby-Users-Group/krug-website#12]
Can we use this code for other RUG site ?
OFC design would be different : )

I really like your site/app/concepts

**Comment by mensfeld** [comment]
@gajewsky can you add MIT to it (if you don't mind MITing the Klaudias design)?

**Comment by choosen** [comment]
knock knock @gajewsky

**Comment by gajewsky** [comment]
@mensfeld @choosen just talked with @hoszka and we are both comfortable with MITing it. Unfortunately I am currently out of town and not able to do it just now. If you want and can do that please go for it :)

**Comment by mensfeld** [comment]
@choosen feel free to PR the MIT ;)
